project:
  type: website
  output-dir: C:/Users/lushg123.stu/Desktop/GIT/E-Portfolio

website:
  title: "Grace Lush"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About Me
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Deliverables
      - href: content.qmd
        text: My MGEM Capstone

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual



